# TechX - Machine Learning Course 

## Assignment 1 - Python and NumPy

This is an introductory assignment to the course. Two fundamental skills that every data scientist must have are math and python. Make sure that you are able to do all of the following questions. If you have trouble, please make sure to ask for help from either the ALs or the mentors. 

In [6]:
def test_function(function, test_cases, test_cases_answers):
    """Runs function through test cases"""
    passed = True
    
    for (case, answer) in zip(test_cases, test_cases_answers):
        output = function(case)
        if output != answer: 
            print('Your output: ', output, '\t Expected output: ', answer)
            passed = False
    
    if passed: 
        print('Test passed.')
    else: 
        print('Test failed.')

## Functions

###### 1) Write a function that calculates the average of an array in an iterative way

In [1]:
def average(array):
    """ Calculates the average of array. Returns average float"""
    avg = sum(array)/len(array)
    return avg
    #=============== YOUR CODE HERE ===================

Run the next cell to test your function.

In [7]:
test_cases_average = [[1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              [0.21780088, 0.4118428,  0.62573827, 0.78184048, 0.96162729, 0.21242742, 0.06843751, 0.70688805, 0.98459559, 0.1153083 ]]

test_cases_answers_average = [1, 5.5, 0.508650659]

test_function(average, test_cases_average, test_cases_answers_average)

Test passed.


### Indexing, Slicing and Iterating

###### 2) Extract the username of these emails. Beware, there may be different domains! You want to return the String before '@'.

Example: <br>
<b>input:</b> 'john.smith@qq.com' <br>
<b>return:</b>'john.smith'

<b>input:</b> 'jennifer@outlook.com' <br>
<b>return:</b>'jennifer' 

In [8]:
def extract_username(email): 
    """Extracts the username from the input email address. Return username String"""
    list_1 = email.split('@')
    return list_1[0]
    #=============== YOUR CODE HERE ===================

Run the next cell to test your function.

In [9]:
test_cases_extract_username = ['john-smith@gmail.com',
              'this.is.the.username@abcdefghijklmnopqrstuvwxyz',
              'invalid-email']

test_cases_answers_extract_username = ['john-smith', 'this.is.the.username', 'invalid-email']

test_function(extract_username, test_cases_extract_username, test_cases_answers_extract_username) 

Test passed.


<hr>

### Complete the following questions using ONLY NumPy

### Linear algebra operations 

###### 3) Import NumPy Library into your Python environment

In [13]:
#=============== YOUR CODE HERE ===================
import numpy as np

###### 4) Create a 10 element vector, x, of random integers between 10 and 15 (inclusive).  

In [15]:
import random 

x = np.zeros([1,10])
for i in range(10):
    x[0][i] = random.randint(10,15)

print(x)# YOUR CODE HERE

[[12. 10. 11. 11. 14.]]
14.0


In [ ]:
# print(max(x[0]))

In [16]:
###### q) Print out the position of the max value of the array. 
print(np.where(x[0]==max(x[0])))
a = np.where(x[0]==max(x[0])) #a is a tuple

(array([4]),)


###### 5) Create a 10 element vector, y, of 1.  

In [ ]:
y = np.ones([1,10]) # YOUR CODE HERE
print(y)

###### 6) Add x and y together

In [ ]:
answer = np.add(x,y) # YOUR CODE HERE
print(answer)

###### 7) Convert the following matrix into a numpy array. 

$\begin{bmatrix}
5 & 10 & 15\\ 
2 &  13 & 23
\end{bmatrix}$

In [18]:
matrix = np.array([[5,10,15],[2,13,23]])# YOUR CODE HERE

print(matrix)

[[ 5 10 15]
 [ 2 13 23]]


###### 8) Transpose the matrix. You should get 

$\begin{bmatrix}
5 & 2 \\
10 & 13 \\
15 & 23 \\
\end{bmatrix}$

In [19]:
matrix_T = matrix.T # YOUR CODE HERE
print(matrix_T)

[[ 5  2]
 [10 13]
 [15 23]]


###### 9) Multiply matrix and matrix_T together. You should get 

$\begin{bmatrix}
350 & 485 \\
485 & 702 
\end{bmatrix}$

In [20]:
matrix_square = np.matmul(matrix,matrix_T)# YOUR CODE HERE
print(matrix_square)

[[350 485]
 [485 702]]


###### q) Print out the determinant of the squared matrix. 

In [21]:
det = np.linalg.det(matrix_square)# YOUR CODE HERE
print(det)

10474.99999999999


###### q) Print out the inverse matrix. 

In [22]:
inv = np.linalg.inv(matrix_square)# YOUR CODE HERE
print(inv)

[[ 0.06701671 -0.04630072]
 [-0.04630072  0.03341289]]


###### q) Print out the eigenvectors and the eigenvalues of the squared matrix. 

In [23]:
eigenvalues ,eigenvectors = np.linalg.eig(matrix_square)# YOUR CODE HERE
print('eigenvalues: ', eigenvalues)
print('eigenvectors: ', eigenvectors)

eigenvalues:  [  10.05329733 1041.94670267]
eigenvectors:  [[-0.81887743 -0.57396842]
 [ 0.57396842 -0.81887743]]


###### q) Check if the eigen properties hold true. 

Remember that the linear transformation by a matrix on its eigenvectors does not change the direction of the vector, only their lenghts. Eigenvalues are the scalars used to 'stretch' the eigenvectors during the transformation. 

$ Av = \lambda v $ 

In [41]:
#=============== YOUR CODE HERE ===================
result_1 = np.dot(matrix_square,[eigenvectors[0][0],eigenvectors[1][0]])
result_2 = np.dot(eigenvalues[0],[eigenvectors[0][0],eigenvectors[1][0]])
print(result_1,result_2)

[-8.23241832  5.77027518] [-8.23241832  5.77027518]


###### 10) Create a 3-element vector with integers of your choice. 

In [40]:
v = np.zeros(3)# YOUR CODE HERE
print(v)

[0. 0. 0.]


###### 11) Multiply matrix and v. 
Be careful, you want to make sure that the dimensions of the two arrays match up. Your vector should therefore be a (3, 1) matrix. Use the <b>shape<b> to see what dimension is <emph>v<emph> and <b>reshape<b> as needed. 

In [42]:
#=============== YOUR CODE HERE ===================
answer = np.dot(matrix, v)
print(answer)

[0. 0.]


###### 12) Flatten matrix into a 6-element vector. 

In [43]:
flatten = matrix.flatten()# YOUR CODE HERE 
print(flatten)

[ 5 10 15  2 13 23]


###### 13) Concatenate the following matrices.

*Note: Don't forget to convert the matrices to numpy arrays first.*

In [46]:
matrix1 = [[1, 2, 3, 4, 5], 
           [6, 7, 8, 9, 10], 
           [11, 12, 13, 14, 15]]

matrix2 = [[16, 17, 18, 19, 20],
           [21, 22, 23, 24, 25],
           [26, 27, 28, 29, 30]]

mat1 = np.array(matrix1)
mat2 = np.array(matrix2)

a) along axis 0. 
You should get 

$\begin{bmatrix}
 1 & 2 & 3 & 4 & 5 \\
 6 & 7 & 8 & 9 & 10 \\
 11 & 12 & 13 & 14 & 15 \\
 16 & 17 & 18 & 19 & 20 \\
 21 & 22 & 23 & 24 & 25 \\
 26 & 27 & 28 & 29 & 30
\end{bmatrix}$

In [ ]:
answer = np.concatenate((mat1, mat2), axis=0)# YOUR CODE HERE 

print(answer)

b) along axis 1. You should get

$\begin{bmatrix}
 1 & 2 & 3 & 4 & 5 & 16 & 17 & 18 & 19 & 20 \\
 6 & 7 & 8 & 9 & 10 & 21 & 22 & 23 & 24 & 25 \\
 11 & 12 & 13 & 14 & 15 & 26 & 27 & 28 & 29 & 30
\end{bmatrix}$

In [47]:
answer = np.concatenate((mat1, mat2), axis=1)# YOUR CODE HERE 

print(answer)

[[ 1  2  3  4  5 16 17 18 19 20]
 [ 6  7  8  9 10 21 22 23 24 25]
 [11 12 13 14 15 26 27 28 29 30]]


### Basic statistics 

###### Create a vector $v$ with 30 random integers from 1 to 20. 

In [48]:
v = np.random.randint(1,20,[1,30])# YOUR CODE HERE 
print(v)

[[12 11 11 13  2  7 19 19 18 19 13 17 13  5 18 15  8 12  3 12 12 18  9 11
   8 19 17 19  9 16]]


###### Print out the median of the list $ v $.

In [50]:
median = np.median(v)# YOUR CODE HERE 
print(median)

12.5


###### Print out the standard deviation of $ v$.

In [51]:
std = np.std(v)# YOUR CODE HERE
print(std)

4.892738383450406


###### q) Randomly sample 5 items from the following list.

In [52]:
list = np.arange(10) 
print(list)

[0 1 2 3 4 5 6 7 8 9]


In [53]:
sample = np.random.choice(list,5)# YOUR CODE HERE 
print(sample)

[1 0 9 9 5]


###### q) Now sample 5 items again from the list, but this time without replacement. 
If you are sampling with replacement, after each sampling, the item you chose is put into the pool and can be chosen again in following samplings. Whereas, the items are removed from the pool and will not be available again if you are not sampling with replacement. 

In [54]:
sample = np.random.choice(list,5,replace = False)# YOUR CODE HERE 
print(sample)

[3 9 0 2 8]


### Now it is time for a (small) challenge 

###### Maximum A Posteriori 
At a very high level, in Bayesian statistics, MAP is an estimate of an unknown quantity that takes into considerations prior assumptions and past events. 
For example, in a coin toss, the theoretical assumption is 0.5 probability of face and tail. However, the probability distribution will change based on the previous results of the coin toss.

Let $x$ be the random variable of the coin toss, with $x$ = 1 being Head and $x$ = 0 Tail. Let $\theta$ be the probability of getting 1. Intuitively, suppose you get 3 heads out of 10 tosses, your $\theta$ value would be $\theta = \frac{head}{total} = \frac{3}{10} = 0.3$.


We can model the coin toss with a Bernouilli equation. 
$\theta = P(x = 1) = 1 - P(x = 0)$. 

The probability mass function of $x$ depending on $\theta$ is then $P(x | \theta) = \theta^x (1 - \theta)^{1-x}$, where $\theta$ is defined by prior data and updated after each iteration. 



The formula to estimate the probability is $ \hat{\theta}_{MAP}(x) = \underset{\theta}{\mathrm{argmin}} P(x | \theta) P(\theta)$

You can read more about MAP here: https://wiseodd.github.io/techblog/2017/01/01/mle-vs-map/


###### Given this, code out a formula that estimates the probability of a BIASED coin landing on HEAD after 20 tosses. 

Assume that you did not know that coin was biased at the beginning, so start with a $P(x = 1) = 0.5$. 
Toss your coin with a bias of $P(x = 1) = 0.8$. After each iteration, print out the total number of Tails and Heads you have gotten, and the updated $\theta$. 

What do you observe? 



In [60]:
#=============== YOUR CODE HERE ===================
toss = 200
total = 0
head = 0
theta = 0.5
sample = np.array([1,1,1,1,1,1,1,1,0,0])
res = np.zeros(toss)

for i in range(toss):
    j=i+1
    print("toss",j)
    print("last theta: ",theta)
    if np.random.choice(sample)==1:
        head+=1
        res[i]=1
    total+=1
    theta = head/total
    print("new theta: ",theta)
    print("---------")

print(res)

toss 1
last theta:  0.5
new theta:  1.0
---------
toss 2
last theta:  1.0
new theta:  1.0
---------
toss 3
last theta:  1.0
new theta:  1.0
---------
toss 4
last theta:  1.0
new theta:  1.0
---------
toss 5
last theta:  1.0
new theta:  0.8
---------
toss 6
last theta:  0.8
new theta:  0.8333333333333334
---------
toss 7
last theta:  0.8333333333333334
new theta:  0.8571428571428571
---------
toss 8
last theta:  0.8571428571428571
new theta:  0.75
---------
toss 9
last theta:  0.75
new theta:  0.7777777777777778
---------
toss 10
last theta:  0.7777777777777778
new theta:  0.8
---------
toss 11
last theta:  0.8
new theta:  0.8181818181818182
---------
toss 12
last theta:  0.8181818181818182
new theta:  0.75
---------
toss 13
last theta:  0.75
new theta:  0.7692307692307693
---------
toss 14
last theta:  0.7692307692307693
new theta:  0.7857142857142857
---------
toss 15
last theta:  0.7857142857142857
new theta:  0.7333333333333333
---------
toss 16
last theta:  0.7333333333333333
new t

<div style="background-color:#F9F2EB; text-align:left; padding: 10px;">
Your dataset description here: ... 